[package]
name = "field32"
version = "0.1.0"
edition = "2021"

[dependencies]
glium = "0.32"
imgui = "0.11.0"
imgui-glium-renderer = "0.11.0"
imgui-winit-support = {version = "0.11.0", default-features = false}
winit = "0.27"